from sys import argv


def main(args):
    fpath = args[0]
    
    # get the include guard
    incguard = '_' + fpath.split('\\')[-1].replace('.h', '').upper() + '_H_'
    
    contents = ''.join((
        '// This file was generated by ', __file__, '\n',
        '\n',
        '#ifndef ', incguard, '\n'
        '#define ', incguard, '\n',
        '\n',
        '#define SOARE_BUILD_TIME    __TIME__\n',
        '#define SOARE_BUILD_DATE    __DATE__\n',
        '\n',
        '#endif // !', incguard, '\n'))
    
    genfile = open(fpath, 'w')
    genfile.write(contents)    
    genfile.close()
    

if '__main__' == __name__:
    if argv.__len__() >= 2:
        main(argv[1:])
    else:
        print("ERROR: expected at least one parameter!\n")